name: Analyse SonarCloud

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build et analyse SonarCloud
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=matheobz_TP-CleanCode \
          -Dsonar.organization=matheobz \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Commenter la PR si l'analyse Sonar échoue
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ L’analyse **SonarCloud** a échoué pour cette Pull Request.

            Merci de corriger les problèmes de qualité avant de merger.
            👉 Voir les résultats ici : [SonarCloud](https://sonarcloud.io/project/overview?id=matheobz_TP-CleanCode)
            
      - name: Notifier Teams si échec
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "summary": "Analyse SonarCloud échouée",
            "themeColor": "FF0000",
            "title": "SonarCloud",
            "text": "L’analyse a échoué sur la branche ${{ github.ref_name }}."
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}